spring:
  jpa:
    database: MySQL
    show-sql: false
    hibernate:
      ddl-auto: validate
  datasource:
    platform: mysql
    url: jdbc:${CLEARDB_DATABASE_URL:mysql://localhost:3306/blog?createDatabaseIfNotExist=true}
    username: root
    password: 1321
server:
  port: 8080
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
