spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/Blog?useUnicode=true&characterEncoding=utf8&createDatabaseIfNotExist=true
    username: postgres
    password: 1321
    driverClassName: org.postgresql.Driver
server:
  port: 8080
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
